language: java
jdk:
  - oraclejdk8

before_install:
  - mysql -u root -e 'CREATE DATABASE testSystem;'
  - mysql -u root -e 'CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';'
  - mysql -u root -e 'GRANT ALL PRIVILEGES ON testSystem.* TO 'user'@'localhost';'

services:
  - mysql

script:
  - ./gradlew build